name = "riggamer"
compatibility_date = "2026-09-07"
main = "dist/_worker.js/index.js"

[assets]
directory = "dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "riggamer-db"
database_id = "0c4ec55d-d64f-4496-8e44-ed780130dc9d"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "riggamer-media"

[vars]
GTM_ID = "GTM-58ZBC3HB"
