-- RigGamer D1 Seed — Articles

INSERT OR IGNORE INTO articles (slug, title, excerpt, cat, date, readtime, img, score, game) VALUES

-- GUIDES
('nte-tier-list','NTE Tier List: Best Characters Ranked (September 2026)','Every character ranked for endgame content, reroll value, and banner priority.','guides','Sep 3, 2026',8,'https://rigpeak.com/wp-content/uploads/2026/08/24/nte-guides.jpg',NULL,'NTE'),
('arknights-endfield-best-operators','Arknights: Endfield — Best Operators for New Players','Which operators to build first and which banners to skip completely.','guides','Sep 1, 2026',10,'https://rigpeak.com/wp-content/uploads/2026/08/24/arknights-endfield-guides.jpg',NULL,'Arknights'),
('project-entropy-beginner-guide','Project Entropy: Beginner''s Guide — First Week Roadmap','Everything you need to know in your first seven days to avoid the biggest mistakes.','guides','Aug 29, 2026',12,'https://rigpeak.com/wp-content/uploads/2026/08/24/project-entropy-guides.jpg',NULL,'Project Entropy'),
('raid-shadow-legends-champion-guide','RAID: Shadow Legends Champion Building Guide 2026','Stats, masteries, and gear sets explained — build your first 60-star champion correctly.','guides','Aug 27, 2026',9,'https://rigpeak.com/wp-content/uploads/2026/08/24/raid-shadow-legends-guides.png',NULL,'RAID'),
('enlisted-beginner-squad-guide','Enlisted Squad Building Guide: Best Soldiers for Each Mode','How to structure your squad for Berlin, Normandy, and the Pacific.','guides','Aug 25, 2026',7,'https://rigpeak.com/wp-content/uploads/2026/08/24/enlisted-guides.jpg',NULL,'Enlisted'),
('once-human-base-building','Once Human Base Building Guide: Defense & Resource Layout','Optimal base layouts that survive weekly resets and maximize resource output.','guides','Aug 22, 2026',11,'https://rigpeak.com/wp-content/uploads/2026/08/24/once-human-guides.jpg',NULL,'Once Human'),
('rise-of-kingdoms-beginner','Rise of Kingdoms Beginner Guide: Best Civilization Tier List','Which civilization to pick, how to speed up your first City Hall levels, and rally etiquette.','guides','Aug 20, 2026',8,'https://rigpeak.com/wp-content/uploads/2026/08/24/rise-of-kingdoms-guides.png',NULL,'RoK'),
('war-thunder-best-nation','War Thunder: Best Nation to Grind in 2026','A tier list of all nations with BR spreads, top-tier vehicles, and grind cost compared.','guides','Aug 18, 2026',9,'https://rigpeak.com/wp-content/uploads/2026/08/24/war-thunder-guides.jpg',NULL,'War Thunder'),
('where-winds-meet-weapons','Where Winds Meet Beginner''s Guide: Weapons, Inner Power & Jianghu','No class lock, eight weapon types — pick your build without wasting early resources.','guides','Aug 15, 2026',10,'https://rigpeak.com/wp-content/uploads/2026/08/24/where-winds-meet-guides.jpg',NULL,'Where Winds Meet'),
('star-trek-fleet-command-guide','Star Trek Fleet Command: Complete Beginner Roadmap','From your first ship to Faction missions — how to progress without spending real money.','guides','Aug 12, 2026',13,'https://rigpeak.com/wp-content/uploads/2026/08/24/star-trek-fleet-command-guides.webp',NULL,'Star Trek'),

-- NEWS
('nte-patch-notes-1-1','NTE Patch 1.1 Notes: New Character, Map Expansion, Balance Changes','Everything in the September update including the Luofu urban area and two new banner characters.','news','Sep 4, 2026',5,'https://rigpeak.com/wp-content/uploads/2026/08/24/nte-guides.jpg',NULL,NULL),
('arknights-endfield-season-2','Arknights Endfield Season 2 Release Date and Roadmap Confirmed','Hypergryph confirms late October content drop with three new operators and a world expansion.','news','Sep 2, 2026',4,'https://rigpeak.com/wp-content/uploads/2026/08/24/arknights-endfield-guides.jpg',NULL,NULL),
('war-thunder-new-vehicles','War Thunder Dev Server: New Vehicles and Top-Tier Changes Datamined','Gaijin''s September dev server reveals major top-tier rebalance and 12 new vehicles.','news','Aug 31, 2026',4,'https://rigpeak.com/wp-content/uploads/2026/08/24/war-thunder-news.jpg',NULL,NULL),
('once-human-season-3','Once Human Season 3: New Scenario, Cross-Server Events Announced','Starry Studio confirms Season 3 launch date and introduces permanent server carry-over system.','news','Aug 28, 2026',3,'https://rigpeak.com/wp-content/uploads/2026/08/24/once-human-guides.jpg',NULL,NULL),
('project-entropy-global-launch','Project Entropy Global Launch: Day One Server Performance & Issues','Server queue times, login errors, and first impressions from the global PC launch day.','news','Aug 26, 2026',5,'https://rigpeak.com/wp-content/uploads/2026/08/24/project-entropy-guides.jpg',NULL,NULL),
('raid-new-champion','RAID Shadow Legends: New Void Legendary Revealed for Fusion Event','Plarium unveils the next fusion Void Legendary — kit details and whether it''s worth the grind.','news','Aug 24, 2026',4,'https://rigpeak.com/wp-content/uploads/2026/08/24/raid-shadow-legends-guides.png',NULL,NULL),
('star-trek-event-recap','Star Trek Fleet Command: Borg Arc Event Guide and Milestones','All milestone rewards, optimal grind paths, and whether the Borg cube refit is worth the tokens.','news','Aug 21, 2026',6,'https://rigpeak.com/wp-content/uploads/2026/08/24/star-trek-fleet-command-news.jpg',NULL,NULL),
('enlisted-update-air','Enlisted Air Superiority Update: Full Changelog and New Maps','Gaijin expands Enlisted''s air combat with three new maps and revised plane unlock trees.','news','Aug 19, 2026',4,'https://rigpeak.com/wp-content/uploads/2026/08/24/enlisted-guides.jpg',NULL,NULL),
('rise-of-kingdoms-kvk','Rise of Kingdoms KvK Season 5 Meta Analysis: Best Commanders','Which commanders are dominating open-field and who got nerfed into irrelevance this KvK.','news','Aug 16, 2026',7,'https://rigpeak.com/wp-content/uploads/2026/08/24/rise-of-kingdoms-news.jpg',NULL,NULL),
('where-winds-meet-ps5-launch','Where Winds Meet PS5 Launch: Cross-Save, Frame Rate Modes Detailed','NetEase confirms PS5 cross-save with PC, 60fps performance mode, and 4K quality mode specs.','news','Aug 13, 2026',3,'https://rigpeak.com/wp-content/uploads/2026/08/24/where-winds-meet-news.jpg',NULL,NULL),

-- REVIEWS
('nte-review','NTE: Neverness to Everness Review — Our Verdict','The best urban open world in gacha gaming, paired with the most player-friendly banner system.','reviews','Aug 24, 2026',9,'https://rigpeak.com/wp-content/uploads/2026/08/31/nte-review-keyart.webp','7.8',NULL),
('arknights-endfield-review','Arknights: Endfield Review — Worth the Four-Year Wait?','Stunning strategy combat and a deep world — undermined by a mid-game content wall.','reviews','Aug 20, 2026',11,'https://rigpeak.com/wp-content/uploads/2026/08/24/arknights-endfield-guides.jpg','8.6',NULL),
('project-entropy-review','Project Entropy Review — The Dark Horse PC Gacha of 2026','Punishing, stylish, and surprisingly fair on the wallet. A genuine competitor to the titans.','reviews','Aug 17, 2026',10,'https://rigpeak.com/wp-content/uploads/2026/08/24/project-entropy-guides.jpg','7.2',NULL),
('once-human-review','Once Human Review — Survival Gaming Meets Live Service','Addictive survival loop and a great seasonal model, but the monetization needs work.','reviews','Aug 14, 2026',8,'https://rigpeak.com/wp-content/uploads/2026/08/24/once-human-guides.jpg','6.5',NULL),
('enlisted-review','Enlisted Review 2026 — Still the Best Free WWII Shooter?','Three years in, Enlisted remains the most immersive free-to-play WWII game on PC.','reviews','Aug 10, 2026',9,'https://rigpeak.com/wp-content/uploads/2026/08/24/enlisted-guides.jpg','6.8',NULL),
('where-winds-meet-review','Where Winds Meet Review — A Wuxia World Worth Getting Lost In','Breathtaking world-building and fluid combat, but the story pacing needs patience.','reviews','Aug 6, 2026',12,'https://rigpeak.com/wp-content/uploads/2026/08/24/where-winds-meet-reviews.jpg','6.4',NULL),
('star-trek-fleet-command-review','Star Trek Fleet Command Review — Strategy or Pay-to-Win?','The license is great, the mid-game is solid, but the late-game monetization is aggressive.','reviews','Aug 2, 2026',8,'https://rigpeak.com/wp-content/uploads/2026/08/24/star-trek-fleet-command-reviews.jpg','6.4',NULL),
('rise-of-kingdoms-review','Rise of Kingdoms Review — Best 4X Mobile Strategy of 2026?','Deep alliance politics and genuine strategic depth, but progress slows after City Hall 25.','reviews','Jul 28, 2026',10,'https://rigpeak.com/wp-content/uploads/2026/08/24/rise-of-kingdoms-guides.png','7.8',NULL),
('war-thunder-review','War Thunder Review 2026 — The Grind vs The Glory','Unmatched vehicular combat depth, but the grind economy and monetization remain controversial.','reviews','Jul 24, 2026',11,'https://rigpeak.com/wp-content/uploads/2026/08/24/war-thunder-reviews.png','7.6',NULL),
('raid-shadow-legends-review','RAID: Shadow Legends Review — Polished Gacha, Familiar Traps','Best-in-class production values and deep champion systems — the monetization is the ceiling.','reviews','Jul 20, 2026',9,'https://rigpeak.com/wp-content/uploads/2026/08/24/raid-shadow-legends-guides.png','8.0',NULL),

-- SETUP
('best-gaming-pc-budget-2026','Best Budget Gaming PC Build 2026 — $600 That Runs Everything','A tested $600 build that hits 60fps on every game in our catalogue including NTE and Project Entropy.','setup','Sep 2, 2026',14,'https://rigpeak.com/wp-content/uploads/2026/08/24/war-thunder-guides.jpg',NULL,NULL),
('best-gaming-monitor-2026','Best Gaming Monitor 2026: 1440p vs 4K vs 240Hz','We tested 12 monitors across three categories. Here are the three worth buying at each budget.','setup','Aug 28, 2026',12,'https://rigpeak.com/wp-content/uploads/2026/08/24/nte-guides.jpg',NULL,NULL),
('gaming-headset-guide','Best Gaming Headset 2026 — PC, PS5, and Cross-Platform Picks','Tested for gaming, Discord calls, and music. Sorted by budget from $40 to $300.','setup','Aug 22, 2026',10,'https://rigpeak.com/wp-content/uploads/2026/08/24/arknights-endfield-guides.jpg',NULL,NULL),
('mechanical-keyboard-guide','Best Mechanical Keyboard for Gaming 2026 — Switch Guide Included','Linear, tactile, or clicky — which switch for which game type, and the three keyboards we recommend.','setup','Aug 16, 2026',9,'https://rigpeak.com/wp-content/uploads/2026/08/24/enlisted-guides.jpg',NULL,NULL),
('gaming-mouse-guide','Best Gaming Mouse 2026 — Lightweight vs Ergo vs Ambidextrous','Seven mice tested across 200 hours. Sorted by grip style, budget, and polling rate.','setup','Aug 10, 2026',8,'https://rigpeak.com/wp-content/uploads/2026/08/24/project-entropy-guides.jpg',NULL,NULL),
('gpu-upgrade-guide-2026','GPU Upgrade Guide 2026: When to Upgrade and What to Buy','Should you upgrade now or wait? A data-driven breakdown of the current GPU market by game and resolution.','setup','Aug 4, 2026',11,'https://rigpeak.com/wp-content/uploads/2026/08/24/raid-shadow-legends-guides.png',NULL,NULL);
